name: run Kamerleden-Aanwezig.py

on:
   schedule: 
     - cron:  '03 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install requests
          pip install bokeh
          pip install pandas

      - name: execute py script # run Kamerleden-Aanwezig.py
        run: |
          python3 Kamerleden-Aanwezig.py --git True
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
